# Config comes exclusively from `--configfile <path>` passed by `bin/jamg run`
# or by a direct `snakemake --configfile ...` invocation. No hardcoded default.
include: "rules/common.smk"
include: "rules/repeats.smk"
include: "rules/rnaseq.smk"
include: "rules/tgg.smk"
include: "rules/pasa.smk"


rule all:
    input:
        f"{OUTDIR}/OGS.gff3",
