name: sif
channels:
- conda-forge
- bioconda
- nodefaults
dependencies:
- augustus ==3.5.0
- evidencemodeler ==2.1.0
- pasa ==2.5.3
- transdecoder >=6.0.0
- repeatmasker >=4.2.3
- repeatmodeler >=2.0.6
- trf >=4.9.1
- trinity >=2.15.0
- minimap2 >=2.28
- gmap *
- star >=2.7.11a
- blast >=2.16
- samtools >=1.21
- bcftools >=1.21
- bedtools ==2.31.1
- htslib >=1.21
- gffread >=0.12.9
- snakemake >=9.0,<10.0
- snakemake-executor-plugin-slurm *
- gcc_linux-64 *
- gxx_linux-64 *
- make *
- autoconf *
- automake *
- libtool *
- pkg-config *
- git *
