#!/usr/bin/env bash
# Phase 3b integration test for workflow/rules/rnaseq.smk.
# Mini-config uses mode=bam; the rule consumes test_suite/mini-rnaseq.bam
# and produces a sorted+indexed bam (passthrough) plus the augustus hint
# file generated by augustus_RNAseq_hints.pl.
set -euo pipefail

REPO="$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"
SIF="$REPO/containers/jamg.sif"
CFG="$REPO/test_suite/mini-config.yaml"
OUT="$REPO/test_suite/output/rnaseq"

if [[ ! -f "$SIF" ]]; then
    echo "ERROR: $SIF not found. Run 'make sif' first." >&2
    exit 1
fi

rm -rf "$OUT"

apptainer exec --bind "$REPO":"$REPO" "$SIF" \
    "$REPO/bin/jamg" run --config "$CFG" --cores "${SLURM_CPUS_PER_TASK:-20}" --until rnaseq_hints

test -s "$OUT/rnaseq.sorted.bam"     || { echo "sorted BAM missing";    exit 1; }
test -e "$OUT/rnaseq.sorted.bam.bai" || { echo "BAM index missing";     exit 1; }
test -s "$OUT/rnaseq.hints"          || { echo "augustus hints missing"; exit 1; }

# At least one coverage-hint line. Empty hints would mean augustus_RNAseq_hints.pl
# silently failed even though the script exited 0.
hints=$(grep -cvE '^(#|$)' "$OUT/rnaseq.hints" || true)
if (( hints < 1 )); then
    echo "rnaseq.hints has no feature rows ($hints)"
    exit 1
fi
echo "OK: rnaseq rule produced $hints hint rows in rnaseq.hints"
