genome: test_suite/mini-genome.fasta
outdir: test_suite/output
threads: 4
species: drosophila
species_category: Diptera
max_intron: 70000
code: TEST
rnaseq:
  mode: bam
  bam: test_suite/mini-rnaseq.bam
trinity_denovo: null
longreads: null
repeats:
  contamination_check: true
  rna_lib: test_suite/mini-repeats-rna.fasta
  species_lib: test_suite/mini-repeats-species.fasta
  species_category: Diptera
proteins:
  swissprot_db: test_suite/mini-proteins.fasta
pasa:
  config_template: workflow/scripts/alignAssembly.config.template
  max_intron_length: 70000
  tmp_dir: /dev/shm
evm:
  weights_file: workflow/config/evm_weights.example.txt
  segment_size: 5000000
  overlap_size: 80000
  extra_gff: []
genemark:
  path: ~/software/gmes_linux_64_4.tar.gz
  key: ~/software/gm_key_64.gz
augustus:
  optimise: false
  extrinsic_cfg: workflow/config/extrinsic.cfg
manual_curations: null
