= Just Annotate My Genome (JAMg)

== Intro 
An increased number of genomes are being made public but few individual research are willing to take ownership of their own data. Indeed, the current model is for genome sequences to be handled by sequencing centers or large bioinformatic repositories (RefSeq or Ensembl). Even though using these widely used and standardized repositories and center is an excellent model to decrease the cost of completing a genome project, this comes at a cost. First, these groups have in-house pipelines built and customized for the projects that financially support them (i.e. small genomes of microbial human pathogens and largely fully complete genomes such as Drosophila or human) rather than say a highly polymorphic species from a natural ecosystem. Second, the lack of a robust funding model means that these repositories are do not have the resources to offer community-wide support and customization of a pipeline. Third, and perhaps most importantly, these centers and repositories usually lack the domain expertise associated with the biology of the species.

For these (and perhaps others?) reasons, genome consortia that have access to genomicists (or PhD students and post-docs willing to learn) are either collaborating with bioinformatic laboratories or investing in their own annotation capability. This endeveavour has been greatly helped by the public availability of the tools used by the repositories and sequencing centers (e.g. GMOD, Ensembl and sequencing-center specific platforms such as those from the Broad Institute). The GMOD project specifically specializes in compact, user friendly solutions that _just_work_. For example, MAKER requires a few minutes of configuration (and a few days or even weeks of computing) to deliver a standardized annotation for gene models. At the other side of the spectrum, Ensembl delivers a comprehensive solution, database and informatic pipelines that - in the hands of a highly-trained bioinformatician - can deliver the same depth and level of annotation as that used by the EBI. There really is no a solution that fits in-between. There is also almost no software that also wishes to educate the user rather than offering a black box. Finally, there is no solution that we know of that can also functionally annotate the genome (a la BLAST2GO but free) and then link the concept of gene model (feature) annotation with functional annotation. 

The JAMg software was created to address the issue of creating gene models (feature annotation) and was built by http://tiny.cc/alexie_pap_csiro/[Alexie Papanicolaou] at the http://www.csiro.au/[Commonwealth Scientific and Industrial Research Organisation] (CSIRO) with some brilliant support from http://www.broadinstitute.org/~bhaas/[Brian Haas] at the http://broadinstitute.org[Broad Institute]. The software and manual are written so that to guide the annotation process so that users can follow the process closely. Even though with JAMg you will not need another genome annotation pipeline, JAMg does not aim to replace other genome annotation pipelines (e.g. each sequencing center has its own): it does aim to support nascent genome annotators and (ultimately) educate its users about genome annotation in general. As part of our Just_Annotate series, JAMg links with JAMp and WebApollo to provide a first solution for users wishing to go from genome assembly to deriving biological hypotheses.

JAMg is far from being a comprehensive solution (see Plugins needed) but it is modular and an open-source software and like our other software we invite the community to provide not only feedback but also additional functionality and suggestions on how to improve it.

== Obtaining JAMg


== Running JAMg

== Plugins needed



